FROM ghcr.io/alis-is/ascend:latest-alpine-ami

COPY bootstrap /bootstrap

ENV ASCEND_APPS=/bake-buddy/
ENV APPS_BOOTSTRAP=/bootstrap

RUN mkdir -p /bake-buddy

RUN wget -q https://github.com/tez-capital/tezbake/raw/main/install.sh -O /tmp/install.sh && sh /tmp/install.sh

RUN apk add --no-cache shadow && \
	useradd -r -s /bin/false ascend
